### ISSUE TITLE
About the IDE

### ISSUE THREAD

**Issue by roberpot** [Sphereserver/Source#10]
Really hate that VS change the code (my last commit has tons of style changes that vs do...). Any way to make vs stop touching the files? CLion licenses are ready? I think i'll switch to codeblocks or clion.

**Comment by coruja747** [comment]
you can change the VS text formatting here:
Tools > Options > Text Editor > C/C++ > Formatting > Spacing

here I leave it everything on default value, and just enabled the "insert space withing parentheses of a control statement" to make (a) become ( a )

it doesn't make much difference, since the current code is using a random style at each file / function, so sometimes this can help, and sometimes VS still formatting thousands lines. But anyway this thing is great to help the code style become more "standard" on all files

**Comment by roberpot** [comment]
I hate to commit code that i do not change, is confusing :(. I'll change that setting. I prefer to wait until we have a "sphere standard".

**Comment by lintax** [comment]
No reply from Intellij so far. Hoping we will get the licenses (but this is not guaranteed - not sure what extra requirements they are holding for this internally).

At the moment you can work using EAP CLion build (pre-release builds), it works pretty well. https://confluence.jetbrains.com/display/CLION/Early+Access+Program
However, it is not always available so you cannot base working on EAP builds all the time.

**Comment by denizsokmen** [comment]
https://gist.github.com/wangkuiyi/7379a242f0d4089eaa75

We can use clang format as a standard. You can attach git commit hook to invoke clang format which automatically formats every changes while you are committing. I used it in a few projects, it's really useful to standardise coding style.

**Comment by lintax** [comment]
Using pre-commit hook is potentially nice but it would require to patch other legacy code in addition to your patch in order to pass for a commit.

Is the code style a problem worth any solution other than disabling auto-formatting code you didn't touch intentionally?

**Comment by coruja747** [comment]
sphere code doesn't have any "stardard style", but if we can choose, it's better let VS use his default style. Since most of us are using VS2010 ~ VS2015, this will make everything plug-and-play and all devs will have the same "automatic formatting" :P

it's not really a problem, just a question of clean GIT commits and better readable codes. If all devs keep using the same format style, the code will only get formatted once. But this can be a pain if each dev use a different formatting and we keep changing the format of the same code many times, like this:
dev A commit -> FunctionName( int A, CChar * pChar )
dev B commit -> FunctionName(int A, CChar * pChar)
dev C commit -> FunctionName( int A, CChar *pChar )
dev D commit -> FunctionName(int A, CChar *pChar)
dev E commit -> FunctionName( int A, CChar *pChar )

**Comment by roberpot** [comment]
Well, i really hate "code to the IDE". I finally change to CLion.

**Comment by denizsokmen** [comment]
I still vote for clang formatter pre-commit hook. It makes C/C++ pretty readable and completely IDE and platform independent. You might wanna give it a try if you have spare time.

**Comment by lintax** [comment]
Disabling code reformat in IDE for lines you did not change, will not make such changes as @coruja747 enlisted.
@denizsokmen insisting some format would probably mean to update the whole source to the same format, that would make lots of style changes and spoil project history (git blame). Personally I prefer not to touch things you did not change.
Moreover, I dislike coding style in several places (for example { on the next line as it makes space in place I do not wish it to be, it is not a problem to make an empty line if logics suggests that) however, editing files formatting this way I obey the rules that are in the code around.
The actual problem, I think, is space-tabs war... This is what you cannot obey manually and should be insisted.

So I im neither for, nor against the proposal. Just do not wish to change line history to be able to review why some line was written, and without reformatting it is easier.

**Comment by lintax** [comment]
The issue is closed, CLion several licences are available. If you have not yet got one, contact me
