### ISSUE TITLE
CURFOLLOWERS not work correctly

### ISSUE THREAD

**Issue by WRWRs** [Sphereserver/Source#106]
Sometimes, when you summon vortex or others and go away, he just destroy buy curfollower slot stay busy
It's old bug and was fixed by scripts 

```
on=@death
if (<memoryfindtype.02>)
memoryfindtype.02.link.curfollower -= <qval <tag0.FOLLOWER> ? <tag0.FOLLOWER> : 1>
memoryfindtype.02.remove
endif
```
```
on=@petdesert
if (<memoryfindtype.02>)
memoryfindtype.02.link.curfollower -= <qval <tag0.FOLLOWER> ? <tag0.FOLLOWER> : 1>
memoryfindtype.02.remove
endif
        
```
```
on=@destroy
if (<memoryfindtype.02>)
memoryfindtype.02.link.curfollower -= <qval <tag0.FOLLOWER> ? <tag0.FOLLOWER> : 1>
memoryfindtype.02.remove
endif
```
now it's FollowerSlots instead tag
need to fix it in core

**Comment by cbnolok** [comment]
Does it happen only with mage spells or also with the newsummon keyword?

**Comment by WRWRs** [comment]
with all summon spells

**Comment by xwerswoodx** [comment]
I don't get what is the bug here? Generally summon spells not removed when you die, so they are still followers, isn't it? Depends on this, it doesn't seem a bug.

**Comment by coruja747** [comment]
its working fine, sphere already have these checks added internally to decrease the owner CURFOLLOWER slots when an NPC die or get released/deserted/transfered/removed/etc

maybe it can be something on your custom scripts conflicting with sphere internal function (eg: your custom script change the CURFOLLOWER value and sphere will also change it too exactly at the same time, making it set an wrong final value, or something like this)

**Comment by WRWRs** [comment]
not using custom scripts and players find this bug with energy vortex for example

**Comment by drk84** [comment]
When using OF_PetSlots the followers number increase when releasing an animal.

**Comment by drk84** [comment]
Always with OF_PetSlots,  summary (gm disabled):
**Vendors**
The Maxfollower cap works when you buy a creature from a vendor.
**Shrinking**
Shrinking will increase the curfollower property (instead of decreasing), unShrinking will increase it (ok).
Shrinking follow the Maxfollower cap.
**Taming**
Taming follows the MaxFollower cap but still allows you to tame the animal.
**Pet commands**
Transfering a pet will increase curfollower property of the receiver normally, but the **transferer** curfollower property will not decrease, but instead will increase or remain the same (usually when at the maxfollower cap)
Transfering pet will follow the Maxfollower cap.
Releasing a pet will  increase the curfollower (instead of decreasing),  sometimes it doesn't decrease or increase at all ( (usually when at the maxfollower cap)

**Comment by coruja747** [comment]
on latest build I confirmed and fixed the taming skill not using MAXFOLLOWER limit

also tested some others problems reported and I can't find nothing wrong, but anyway, I rewrote the entire OF_PetSlots engine and now it seems to be faster and more reliable, so try update to latest build to check if these problems still occur
