### ISSUE TITLE
Spellbook crash when opened by macro and backpack is closed.

### ISSUE THREAD

**Issue by drk84** [Sphereserver/Source#115]
Tested with client 7.0.2.0 and 7.0.58.12

If the spellbook is in the backpack (not wielded in hand), closing the backpack and opening the spellbook by macro will cause the client to crash.

Steps:
Create a spellbook
Put in the backpack
Close backpack
Press alt b or the related spellbook macro.

I don't know if it's a client issue or server, but when doing tests i noticed a sysmessage like "You can't reach it there".

**Comment by drk84** [comment]
Script fix:
ON=@Spellbook
pack

**Comment by coruja747** [comment]
this is not really related to the player backpack, spellbook packets works like an container, it open the empty gump and fill it with data. But bad things will happen (freeze, crash, etc) if the client try to open an gump when the item related to this gump (spellbook) is not loaded yet

that's why it crash when it uses "open spellbook" macro with the spellbook inside an closed backpack. So maybe the best fix for this is not force the client open the backpack, but just make it load the spellbook item instead (without open the entire backpack)

honestly I'm a bit busy this week so I can't test it properly, but if you have access on sphere source, on function CClient::addSpellbookOpen() [CClientMsg.cpp] try replace these lines
```
OpenPacketTransaction transaction(this, PacketSend::PRI_NORMAL);
addOpenGump(pBook, GUMP_NONE);
```
with this
```
addItem(pBook);
OpenPacketTransaction transaction(this, PacketSend::PRI_NORMAL);
addOpenGump(pBook, GUMP_NONE);
```

**Comment by drk84** [comment]
Yes, adding that line seems to fix the problem :)
