### ISSUE TITLE
botnet & zombi attack sphere lag & exploding.

### ISSUE THREAD

**Issue by G-Defender** [Sphereserver/Source#118]
Hi sphere 56b and 56c and 56d botnet & zombi attack sphere lag & exploding.
They are using a VPN program. 2000k has a rope entry and exit.
The sphere is flowing like water. It must be a solution.
I use the 56b sphere. How can we fix this problem?

```
04:33:1f4:Client connected [Total:1] ('88.236.21.214' 1/1)
21:28:17c:Client disconnected [Total:69] ('88.236.21.214' 1/1)
```
Logfiles: [bayram.txt](https://github.com/Sphereserver/Source/files/1346439/bayram.txt)

![96a61929-c2a7-41f4-9103-83ea6ae4a487](https://user-images.githubusercontent.com/17534859/31046295-c74d47d4-a5fe-11e7-9994-1b64b4f12533.jpg)
![cbba49fb-9124-4e84-a775-503492f57ccf](https://user-images.githubusercontent.com/17534859/31046296-c75907f4-a5fe-11e7-9732-5af2eb22943d.jpg)

**Comment by coruja747** [comment]
you're under an DDoS attack on layer 7, unfortunately there's nothing we/you can do on sphere-side. To block an DDoS attack you will need an advanced knowledge in network security, and depending on the attack scale you will also need an big $$ to pay anti-DDoS protections

basically, an global network have many layers (1 to 7)
-layer 1: is the infected/attacker PC
-layer 3: is your datacenter
-layer 7: is your application (Sphere)

if connections are reaching your application (layer 7) this means that they passed through all the others layers without being been blocked. So you must block these connections on these others layers to prevent they reach your application. You can't simply block them on Sphere or on the PC firewall, because the PC will keep receiving hundreds of connections per second and will keep wasting CPU/RAM/network to block all these connections. So you will need an external anti-DDoS protection to prevent all these connections to reach your server

if you're lucky, maybe your datacenter can offer an basic anti-DDoS protection for cheap price and this will be enough to block the attack. Or you can move to another datacenter that offer this cheap protection (like OVH). But if the attack is really huge and keep coming 24h/day, you will have to pay an advanced DDoS protection from an anti-DDoS leader company (F5, Incapsula, Arbor, Akamai, etc) for about U$500 ~ U$2000 (per month)
