### ISSUE TITLE
FlipDroppedItems Broken

### ISSUE THREAD

**Issue by xwerswoodx** [Sphereserver/Source#119]
FlipDroppedItems setting in Sphere.ini is broken. I set it to 1 and drop items on the ground but it doesn't flip. I tried to add FLIP=1 on itemdef but still not working, but when I try .xFlip it works.

Basically I solved my problem like this (I share it maybe there is anyone else need it) but if you fix it on sphere build, it could be nice.
```
On=@ItemDropOn_Ground
IF (<EVAL <SERV.RTICKS> - <ACT.dTAG0.AE_TIME>>)
  ACT.FLIP
ENDIF

On=@ItemCreate
IF (<dSERV.ITEMDEF.<ACT.BASEID>.FLIP>)
  ACT.TAG0.AE_TIME=<SERV.RTICKS>
ENDIF
```

**Comment by coruja747** [comment]
I found the problem, it's the `pItem->IsMovableType()` here on this line:
https://github.com/Sphereserver/Source/blob/eefc6bdde3844c7469d123fba0d707ce0d2d607b/src/graysvr/CCharact.cpp#L1857

on UO files some items are not movable by default (eg: spinning wheel) so this function will return "false" making the item not flip. If this check got removed, the problem will be fixed and the spinning wheel will be flipped

but honestly I'm not sure if this is the best way to fix it, because this will really mess things for GMs. Just imagine the mess that will be if an GM is decorating some city buildings and **every** wall/floor/roof/door/stair/etc he place on ground get flipped to an unwanted ID
