### ISSUE TITLE
TDATA3=0 in ranged weapons not work

### ISSUE THREAD

**Issue by WRWRs** [Sphereserver/Source#123]
trying to make bow that can shoot without arrows
TDATA3=0 not work in latest sphere

**Comment by coruja747** [comment]
this is not really an bug, since the source is intended to ~always~ use ammo on t_weapon_bow weapons, the only exception is throwing weapons because they just throw itself (like an boomerang) instead use ammo

anyway I will take a better look later, it will be interesting make TDATA3=0 ignore ammo checks on ranged weapons

**Comment by WRWRs** [comment]
it work fine in old spheres and in source2 :)

**Comment by coruja747** [comment]
try using latest build https://github.com/Sphereserver/Source/commit/953b4ca20272dc9e5f405fe4da467f8c864e99bc, I did some changes that maybe will do the trick

**Comment by WRWRs** [comment]
yes! now it work! Thnx
