### ISSUE TITLE
PacketDeathAnimation=1 not work fine

### ISSUE THREAD

**Issue by WRWRs** [Sphereserver/Source#143]
PacketDeathAnimation=1 not work fine
Players after death freezing
Console gets random unknown packets recieved
and message about account already online

**Comment by coruja747** [comment]
this seems to be a packet mismatch on some clients. It's working fine for me, but for some unknown reason it doesn't work for some ppl

the current PacketDeathAnimation=1 will send the packet 02c to client twice, you can use this function to simulate it: 
```
[FUNCTION TestPacketDeathAnimation]
// Usage: SENDPACKET 02c B[mode]
// Mode:
//  0 = ServerSent
//  1 = Resurrect (unused)
//  2 = Ghost
SENDPACKET 02c B0
SENDPACKET 02c B2
```
so try test it using only 1 single packet (B0 **or** B2) to check if it works. If the crash stop, I can commit this change to the source code

**Comment by WRWRs** [comment]
```
00:13:2:'owner' commands 'sendpacket 02c b0'=1
00:13:WARNING:2:Unknown game packet (0x30) received.
00:13:2:'owner' commands 'sendpacket 02c b2'=1
00:13:2:'owner' commands 'sendpacket 02c b2'=1
00:13:2:Account 'owner' already in use
00:13:2:'owner' commands 'sendpacket 02c b0'=1
00:14:2:'owner' commands 'sendpacket 02c b0'=1
00:14:2:Account 'owner' already in use
00:14:2:Account 'owner' already in use
00:14:2:Account 'owner' already in use
```

sendpacket 02c b0 - crash
both send smsg about already online
using client 7.0.18

**Comment by coruja747** [comment]
try close/open the client between each test, because if a single packet get messed, it will make the client mess all the others packets too (until you close the client and open it again). On your example, the 1st try was enough to crash the client, invalidating the result of all next tries

but anyway, since on your 1st try the client crashed with packet B0, maybe it should work if you use only the packet B2
