### ISSUE TITLE
Function in Argv not working

### ISSUE THREAD

**Issue by canavar2212** [Sphereserver/Source#151]
[Function Test]
SYSMESSAGE <ARGV[0]> <ARGV[1]> 

.TEST 5,1

function not working.? for example output sysmessage: 0 0

**Comment by MariusVendetta** [comment]
ARGN1, ARGN2 and ARGN3 are set for functions with numeric arguments.
So whenever possible, use these instead
  of argv. Example: "myfunction  123 50 89" - these 3 values will be
parsed into argn1, argn2 and argn3


Changed StrArg / StrEat to stop at either a space or a comma. These
are quick functions
  when you just want to take one argument from a string, or just want
the string after one
  argument. Imagine you have a function that takes 1 number and a
string. Instead of using
  argv[], you could use strarg to get the number and streat to get the string.





Marius

Il Sab 21 Lug 2018, 07:20 canavar2212 <notifications@github.com> ha scritto:

**Comment by canavar2212** [comment]
I know I can use it in some way. but there is also the use of argv in the script pack that sphere publishes in its own. Will not the use of argv be anymore?

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/363730491a2253aabfc90506958b1a1ea8209c9f
