### ISSUE TITLE
.scp Path

### ISSUE THREAD

**Issue by canavar2212** [Sphereserver/Source#152]
Hello,

Sphere does not read a loaded script file while starting sphere. Some are reading some, others are reading. Sphere will not see that file even if loaded with serv.load after opening it.

**Comment by coruja747** [comment]
if the problem is only on server startup, probably the file is being loaded on wrong order.
Eg: **file1.scp** defines **[ITEMDEF i_item1]** and **file2.scp** uses this **i_item1**, but **file1.scp** is only being loaded after **file2.scp** and sphere will throw "undefined itemdef i_item1" while loading **file2.scp**

to fix this, try add this specific file on your spheretables.scp [RESOURCES] list, making sure to add it on correct order

**Comment by canavar2212** [comment]
the order is correct, I try all the sequences. Loading scripts/items/magic/sphere_item_magic_weapon.scp There is only one article in the file. sphere loads it smoothly, sees it, but things do not come up.

**Comment by coruja747** [comment]
sounds weird. You already checked the order on sphere startup log? Try delete the .scp file and create another one, this should fix the file encryption if it have some win/linux/UTF/ASCII/etc text encryption problem
