### ISSUE TITLE
Spell configure in sphere.ini and more

### ISSUE THREAD

**Issue by canavar2212** [Sphereserver/Source#158]
hello some settings should be added. these settings must be outdated.

for example ;

old field position 
![old field](https://user-images.githubusercontent.com/10347131/46766475-c4256a00-ccea-11e8-9216-e199bbc7e672.png)

new field position 

![new field](https://user-images.githubusercontent.com/10347131/46766584-0d75b980-cceb-11e8-805b-09e27707d7b1.png)

can this be added to the .ini file?

for example FieldsPZ=0-1

also 

can the time synchronization of the fields be the same as before?

for example ;
https://www.youtube.com/watch?v=Msw6wdhe5fY

Is it possible to have a setting in this schedule?

ex. FieldDurationSync=0-1

and 

Can this type of functions be added?

f_onserver_itemcreat
f_onserver_charcreat

f_onserver_itemdeleted
f_onserver_chardeleted

f_onserver_resync_failed
f_onserver_resync_start
f_onserver_resync_success
f_onserver_resync_restart
f_onserver_item_spawned or @ItemSpawnTimeLoad
f_onserver_char_spawned or @CharSpawnTimeLoad trigger

**Comment by coruja747** [comment]
Unfortunately there's no way to make fields items be created on same Z, because this was an old bug and the bug get fixed. As you can see on the img, on "old position" the field get created inside the grass, which doesn't make much sense. So this got fixed and now it follow proper ground Z

And some days ago I changed LOCAL.Duration on spell triggers to accept 2nd argument to make random values, so you can update to this build and use this feature to make each field item use a random duration (timer) value
```
29-11-2019, Coruja
...
Changed: Some changes on spell triggers (@Effect/@Success [spells] / @SpellEffect/@SpellSuccess [chars]) to allow more customization
	-LOCAL.Duration now accept an 2nd argument to return random values (eg: LOCAL.Duration=60 will return 60, and LOCAL.Duration=60,80 will return a random value between 60,80)
```
