### ISSUE TITLE
time items on character issues 

### ISSUE THREAD

**Issue by canavar2212** [Sphereserver/Source#159]
items that have a timer on the character do not function after a while. including potion cooldown. It disappears when you delete the character and then turn it back on, but after a while it breaks down again and the timer remains in 0. All-time items on the character freeze after a while and the timer remains at 0.
![timerproblem](https://user-images.githubusercontent.com/10347131/46893377-5e1b1d00-ce79-11e8-8213-c579d0b8d5d0.png)

**Comment by GMVader** [comment]
having this issue, is there any way to re-activate all those timers with 0 value?

**Comment by canavar2212** [comment]
this problem is still going on. can you help?

**Comment by coruja747** [comment]
usually it's not a good idea add custom code to default memory items (i_rune_*, t_spell, etc) because these memories have their own behavior, and things could go wrong if you try to change this default behavior

using Poison spell as example (i_rune_poison), the poison memory is created with initial MORE1 = poison strength, and initial TIMER=5. When it reach TIMER=0, it will deal the poison damage, reduce MORE1 a bit, and set TIMER=5 again to start another loop, and will keep doing this loop until MORE1 reach 0 and the poison effect disappear. So you will have some problems with this specific memory item if you try to change the timer manually or use @Timer trigger

to avoid this problem you must create another new custom memory using t_eq_memory_obj, like this:
```
[ITEMDEF i_memory_something]
ID=i_memory
TYPE=t_eq_memory_obj
NAME=Custom memory
ON=@Create
   TIMER=10
ON=@Timer
   SERV.B Custom memory had reached TIMER=0 and got removed
   REMOVE
   return 1
```

**Comment by Seokotov** [comment]
> usually it's not a good idea add custom code to default memory items (i_rune_*, t_spell, etc) because these memories have their own behavior, and things could go wrong if you try to change this default behavior
> 
> using Poison spell as example (i_rune_poison), the poison memory is created with initial MORE1 = poison strength, and initial TIMER=5. When it reach TIMER=0, it will deal the poison damage, reduce MORE1 a bit, and set TIMER=5 again to start another loop, and will keep doing this loop until MORE1 reach 0 and the poison effect disappear. So you will have some problems with this specific memory item if you try to change the timer manually or use @Timer trigger
> 
> to avoid this problem you must create another new custom memory using t_eq_memory_obj, like this:
> 
> ```
> [ITEMDEF i_memory_something]
> ID=i_memory
> TYPE=t_eq_memory_obj
> NAME=Custom memory
> ON=@Create
>    TIMER=10
> ON=@Timer
>    SERV.B Custom memory had reached TIMER=0 and got removed
>    REMOVE
>    return 1
> ```
using this
[ITEMDEF i_MEMORY_patient]
ID=i_MEMORY
TYPE=t_eq_script
NAME=Memory patient
ON=@CREATE
ATTR=attr_decay

ON=@EQUIP
TIMER=3

ON=@TIMER
REMOVE
RETURN 1

**Comment by canavar2212** [comment]
the problem appears on all timers. The potion cooldown and handr1 memories are the default and the settings you specify. but the problem continues.
