### ISSUE TITLE
Hash

### ISSUE THREAD

**Issue by canerksk** [Sphereserver/Source#164]
Can sha be added as encryption? 

Ex. 

HASHMD5 x added HashSha1 x and HashSha256 x

**Comment by coruja747** [comment]
I already thought about this some time ago but honestly it doesn't worth, it's a feature that won't make the server more secure

of course SHA1, SHA256, SHA512, etc have an stronger hash than MD5. But clients don't send hashed passwords to server, the hash is used only on server-side to check the password and to save the account password on sphereaccu.scp. And since this file should never be shared or leaked, it doesn't make much difference if the hash is MD5 or SHA

so you can make passwords more secure using ClientLoginMaxTries / ClientLoginTempBan to avoid brute force attacks than trying to increase the password encryption hash

**Comment by canavar2212** [comment]
In fact, it was aimed at integrating 3 party (wordpress, vbullettin, xenforo) applications. I plan to use it with the purpose of dialer. many platforms no longer prefer md5 encryption thank you for your attention though.

**Comment by GitMadKing** [comment]
in X i use bcrypt to integrate with joomla
my client login is always querying the local db for let client connect.
actually sphereacct password doesn't matter

Marius

Il 07 gen 2019 01:46, "canavar2212" <notifications@github.com> ha scritto:

In fact, it was aimed at integrating 3 party (wordpress, vbullettin,
xenforo) applications. I plan to use it with the purpose of dialer. many
platforms no longer prefer md5 encryption thank you for your attention
though.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Sphereserver/Source/issues/164#issuecomment-451791491>,
or mute the thread
