### ISSUE TITLE
ARROWQUEST closed notworking

### ISSUE THREAD

**Issue by canavar2212** [Sphereserver/Source#166]
ARROWQUEST

ARROWQUEST 0,0,38

functions do not close questarrow.

The concealer under tracking ON=@ABORT triggers in the default sphere_skills.scp file also does not work.

Thank you.

**Comment by coruja747** [comment]
both ARROWQUEST and tracking skill are working fine here on latest build + client 7.0.74.28

this ARROWQUEST function is a bit tricky because clients can show many arrows at the same time, where each arrow must have an different id (index) and this value should be used properly to make the client close the proper arrow. So if you use ```ARROWQUEST 123,123,55``` the client will consider it as arrow 55 and it should be closed using ```ARROWQUEST 0,0,55```. So try check if you are opening/closing the arrow using index value correctly

**Comment by canavar2212** [comment]
I understand. RESOLVED
