### ISSUE TITLE
Weight of item

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source#184]
When I have an item weight=7

In the game it's egal 0.7 stones. If I want a correct weight, I must add 7.0 on the script.

This " problem" is patchable or we must change the weight of all our item?

Thx.

**Comment by coruja747** [comment]
Usually in math we consider that an number with no decimals (1) is already a full integer (1.0), but that's not the same as an programming language using values in tenths, where the full value is the full tenth

On sphere, weight is counted using tenths, so WEIGHT=7 is the same of 0.7. To make this value more "user-friendly" you can explicitly set the "." (like WEIGHT=0.7 or WEIGHT=7.0) to make sphere automatically convert it. This doesn't mean that an value is right and the other is wrong, because both ways (with or without ".") should work fine:

```
WEIGHT=7                 = 7/10  = 0.7
WEIGHT=0.7 = (0.7*10)/10 = 7/10  = 0.7

WEIGHT=70                = 70/10 = 7.0
WEIGHT=7.0 = (7.0*10)/10 = 70/10 = 7.0
```

**Comment by Jhobean** [comment]
Thx  Coruja for the explication. It's good to me to learn that.I understand the logic but how on the old sphere server(55i) the weight 7 worked well? 
At this time, I need to know if it's possible to patch the core or if I modify all my weight in the script.

Thx again for your help.

**Comment by Nirad** [comment]
@Jhobean it's fix no ????

**Comment by Jhobean** [comment]
Fix no. Fixable, I don't know.  Since we are in 56D we must add .0 on all item (including sphere base item). On 55i you don't need.

**Comment by coruja747** [comment]
Honestly this is easily "fixable", it just need to remove an *10 or /10 from some internal weight formulas.

But it's not a good idea change it, since most servers around the world are already using this current format since a long time ago, which is the same since 55r. So if you're using 55i scripts (which is even older) maybe it's better just update these scripts on this single server instead change sphere core which will require all servers already using updated scripts have to update all these scripts again

**Comment by Jhobean** [comment]
Thx for explication  Coruja.
