### ISSUE TITLE
Decay timer

### ISSUE THREAD

**Issue by Khaldor48** [Sphereserver/Source#198]
When drop on ground item with attribute (attr_static or attr_move_never) it should have timer -1.
Now when I drop this item with those attributes (I tried standalone & combination as well) it gets regular decay timer.

**Comment by Khaldor48** [comment]
ERROR:UID=04000543f, id=0468e 'Trap', Invalid code=2236 (Item flagged as decay but without timer set)

it's trap item and on=@Step I'm setting timer 

after few timers it's removed even if I have this applied

on=@Timer
timer -1
return 1

**Comment by coruja747** [comment]
I think it's working fine, things should not be confused because attr_move_never will define if the item will be movable or not, and attr_decay will define if the item will decay or not. So attr_move_never will make the item not movable but it still able to decay

To make the item static forever without decay, you must set attr_move_never (or attr_static) and also make sure to remove attr_decay and set TIMER=-1. Probably this is what you're doing wrong, because this error "item flagged as decay but without timer set" means that the item have attr_decay with TIMER=-1, which doesn't make sense because sphere expects that items with attr_decay should decay. To fix this you must set the item timer correctly (to make it decay) or make sure to remove attr_decay and set TIMER=-1

**Comment by Khaldor48** [comment]
Behaviour few releases ago: 
I create item, I set attr to attr_static or attr_move_never (therefore it doesn't have other attributes). I drop the item on the ground and timer is always -1 even not needed to handle it via @Timer trigger.

Behaviour now:
I create item, I set attr to attr_static or attr_move_never (item doesn't have attr_decay) and when dropped on the ground the timer is set. After timer expires sphere throw error about "item flagged as decay but without timer set"

![image](https://user-images.githubusercontent.com/22933400/65370254-f8bdd780-dc56-11e9-88a0-f2408ab386f1.png)

![image](https://user-images.githubusercontent.com/22933400/65370256-01aea900-dc57-11e9-8041-6a8d58d1dad2.png)

These info images are taken right after Drop on the ground

**Comment by Khaldor48** [comment]
After Timer pass item will decay and dissapear. Event if when I'm handling @Timer as mentioned before

on=@Timer
timer -1
return 1

after Nth timer trigger item also dissapear

**Comment by FiLoUs64** [comment]
Did you trie .static command for adding your items?

**Comment by Khaldor48** [comment]
Thank you for your answer.

[FUNCTION static] //by Thomas20198701
ARGS=<DEF0.<ARGS>>
IF (<SERV.ITEMDEF.<dARGS>>)
 TARGETFG static_ <ARGS>
 SYSMESSAGE <DEFMSG.where_to_place> <SERV.ITEMDEF.<ARGS>.NAME>?
 return 1
ENDIF
SYSMESSAGE <DEFMSG.cmd_invalid>

[FUNCTION static_]
SERV.NEWITEM <ARGS>
NEW.ATTR |= 010
NEW.TIMER=-1
NEW.P=<SRC.TARGP>
ACT=<NEW>

It means it add certain item by ID, and extend attribute with attr_static

So it is the same as adding item via .add and then add attribute attr_static.. the behaviour remains same

**Comment by coruja747** [comment]
This is not really a bug, because as explained, "decayable" and "movable" properties are different things and they're not linked to each other, so items with attr_move_never / attr_static can also decay if they have attr_decay set, and there's no problem if an item with attr_move_never dropped on ground start its decay timer

But anyway, after take a look on the code I found that old builds really don't start the decay timer when drop non-movable items on ground, so to prevent different behavior between builds I just added back this old behavior on the code. So try using latest build to check if it's working fine now

**Comment by Khaldor48** [comment]
Thank you. In latest build it works.
```
attr_decay			00002   // timer currently set to decay.
```
If item has attr= 0 then it should not decay? Because if I set attr to 0 then sometimes I get message 
```
17:14:ERROR:Timer expired without DECAY flag 'Cutlass of Might' (UID=040007c78)?
```
and sometimes item decay even wihtout attr_decay attribute and throw no message in console.

**Comment by coruja747** [comment]
Yes items with ATTR=0 (or in other words, without attr_decay set) should not decay, that's why sphere throw this console error when item timer expires but the item doesn't have attr_decay, because sphere was expecting that items with timer should decay but this specific item doesn't have attr_decay set

If the item decay even without attr_decay set it's because only this specific item have some kind of specific behavior that replace the default timer expired action, like scripts with return 1 on @Timer trigger blocking the decay, or lighsources items that when reach TIMER=0 it will only consume 1 light instead decay, etc
