### ISSUE TITLE
NPCs sell menu problems

### ISSUE THREAD

**Issue by FiLoUs64** [Sphereserver/Source#218]
I found two problem in NPC sell menu.

First with architect, the price of the deed are impossible to change with VALUE in script. 

Also the price are incorrect and randomly in the menu :

https://cdn.discordapp.com/attachments/579309906532761630/649799261726179338/unknown.png

https://cdn.discordapp.com/attachments/579309906532761630/649799287454040074/unknown.png

The other problem is the image of the sellin item are not correct in all the case. When you buy a muffin you will see the image of a pizza.

https://cdn.discordapp.com/attachments/579309906532761630/649800973899923463/unknown.png

**Comment by Jhobean** [comment]
https://forum.spherecommunity.net/Thread-NPC-sell-menu-strange-BUG

**Comment by coruja747** [comment]
I already tried to "fix" this deed value some time ago, but taking a look at the code I found that this is intentional so I just keep it as it is.
Deeds are just a "representation" of some item, so they inherit the VALUE of this item (MORE=i_something) instead use deed value. So this number is not random, it got inherited from the value set on m_stone_and_plaster_house and this is where you can change it

And the gump images are working fine here. What client version you're using? Try create an i_muffin manually to check if the problem is the item using wrong ID, or maybe it could be some duplicated DEFNAME=i_muffin on scripts

**Comment by Jhobean** [comment]
We Using orion.

**Comment by Jhobean** [comment]
For the Price, your right thx. The subtility is you need to fix the value of the deed to 1. If there is no value set, its impossible to buy it...

About the bug of display, we will try another client.

**Comment by FiLoUs64** [comment]
Yeah it's a problem with Orion. Thanks for your help.
