### ISSUE TITLE
Sphere wrong encryption attack DDOS

### ISSUE THREAD

**Issue by dicataldisky** [Sphereserver/Source#221]
Hello, I am receiving several connection attempt ddos ​​attacks, what happens even if unsuccessfully it ends up shard very laggy, can anyone tell me what can be done to simply ignore these attacks?
![unknown](https://user-images.githubusercontent.com/26310007/69923495-117f1080-1484-11ea-80b1-14a28df6cab7.png)

**Comment by coruja747** [comment]
You're just getting about 6 connections per minute, which is really far from an real DDoS that will try about 10k+ of connections per second

But anyway, assuming that this could be an possible application-layer DDoS (when DDoS reach your application), unfortunately there's nothing sphere can do to avoid this, the best protection is set a physical firewall above your server to drop these connections before they reach your server

**Comment by dicataldisky** [comment]
The question is that even with only 5 attempts the sphere is absurdly slow for those already connected!

This problem is caused by 3 people who want to end Ultima Online in Brazil, I blocked IPS directly on TAG [BlockIP] inside SPHERE.INI and also changed UseCrypt = 1 to 0, all normal, I will wait for the next attacks. Thank you!

**Comment by dicataldisky** [comment]
Coruja, I'm trying to figure out how these attacks are made to try to prevent, would you tell me how they are performed?

**Comment by coruja747** [comment]
Unfortunately there's dozens of DDoS types, and each one should be mitigate in a different way, so there's no 1-button-fix. The only way to mitigate an DDoS attack is have a really higher knowledge about network security to understand exactly whats happening and apply the best fix for this specific scenario

DDoS mitigation companies like akamai, incapsula, etc know that everyone need these DDoS protections but nobody have knowledge/tools, so they started to sell technical support and solutions for a lot of money, so these server admins must choose pay or shutdown the server and unfortunately that's why many UO servers are dying

**Comment by dicataldisky** [comment]
I agree, I am working with IP band blocking, directly on the firewall and also on the BLOCK SPHERE.INI, apparently solved, because the BOTS used are usually with IP from other countries, I believe that for Brazil the problem is easier To solve, now who uses international servers already complicates a little.

One thing that I think will help is simply that it ignores non-username and password connection packets on first authentication, but I don't know if it's possible.
