### ISSUE TITLE
Can't delete character with plevel 1 account

### ISSUE THREAD

**Issue by FiLoUs64** [Sphereserver/Source#235]
You can't delete a character with plevel 1 account. With plevel 7 it work.

https://cdn.discordapp.com/attachments/597989183818301441/682650128024469504/Ultima_Online_-_Florenz_Kamar_lHumain_Naurul_Cryptonite_2020-02-27_13-07-17.mp4

Any setting for that or Bug?

Thanks

**Comment by coruja747** [comment]
It seems to be working fine here, what client version are you using?

When the client click to delete char, the server send back another packet telling if the char can't be deleted because it's not old enough / still connected ingame / etc, as you can see here
https://github.com/Sphereserver/Source/blob/d528b27af810f8c0d6260c3182f801f4e743c6f8/src/graysvr/CClientMsg.cpp#L3570
But for some unknown reason your client is not showing this response packet, so maybe this should be something on client-side and not on server-side

**Comment by FiLoUs64** [comment]
Yes thanks. I always forget to test with Classic Client as we are using Orion. I will test and close if everything is working fine.

**Comment by FiLoUs64** [comment]
Works fine with Classic Client (test with 7.0.74.28)

OrionUO/CrossUO Problem

Thanks again for your help.
