### ISSUE TITLE
Misc party issues

### ISSUE THREAD

**Issue by cbnolok** [Sphereserver/Source#29]
PARTY.CREATE 0/1, <UID_master>, <UID>_other gives in console:
ERROR:Undefined symbol 'CREATE' ['CREATE']
ERROR:Undefined keyword 'PARTY.CREATE'

IF (<PARTY>), if i am not in a party, gives in console:
ERROR:Can't resolve <PARTY>
ERROR:Undefined symbol ''
I know there's IsInParty, but i thought it was something to report.

Also, is it possible to add a parameter to ADDMEMBER and ADDMEMBERFORCED to request /accept or to force the joining? A syntax like PARTY.CREATE would be good -> msg,uid(s) where msg is 0/1 sending default sysmessages or not.
(i found PARTY.CREATE in the revisions changelog, but it isn't mentioned in the wiki)

**Comment by coruja747** [comment]
this function PARTY.CREATE is working? Because I'm looking it here, and it seems to be different from changelog description

on changelog the usage is PARTY.CREATE [msg 0/1], [UID 1], ... [UID 9]
but on the real code, it works as PARTY.CREATE [UID 1]

anyway I tested using both sintaxes and both doesn't work

so honestly I don't know what sintax is correct to be used, maybe this could be a job to @nefthon who added this function some years ago :P

**Comment by nefthon** [comment]
Someone should've touched it after me because it was working when I added it. I'll take another look when me and roberpot finish the source's revamp, since there are A LOT of changes and don't want to mess different works.
