### ISSUE TITLE
FACE with more than 1 arguments makes sphere crash

### ISSUE THREAD

**Issue by cbnolok** [Sphereserver/Source#33]
As title, if you do "FACE 1,2" or "FACE 1 2" sphere will crash (i know it should work with an UID as argument, but returning an error would be more appropriate and you can make a living shard crash for a weird mistake). Notably, ".show face 1 1" or ".show 1,1" won't make sphere crash but shows DEFMSG.cmd_invalid.
Also, i suggest to make FACE work with coordinates, in case you want as example to turn to a ground target.

**Comment by lintax** [comment]
does not crash for me on linux, do you have a stack trace?

**Comment by cbnolok** [comment]
I'm on windows and nope, no message on console.

**Comment by coruja747** [comment]
confirmed, it crash SphereSvr.exe on windows, probably because FACE initialize the args variable using piCmd[1] (to store only 1 value) and will give memory leak if try to store more values

but anyway I already fixed it, now it should work fine
https://github.com/Sphereserver/Source/commit/3cdc3699f6dc2554c3326bbba310bb078def8a32
