### ISSUE TITLE
TOL New Trade System bugs

### ISSUE THREAD

**Issue by GODEXTREME** [Sphereserver/Source#7]
I've found 3 bugs on the new trade system:

1 - Current char name isn't showing properly on trade gump.

Example:
My char name: asd
Other char name: asdasd

Then I change the char names:
asd -> EXTREME
asdasd -> whatever

'EXTREME' open a trade with 'whatever' or vice-versa

Gump on 'EXTREME': 'asd' and 'whatever'
Gump on 'whatever': 'asdasd' and 'EXTREME'

2 - Suppose that I have 1 Platinum (in this case, I have exactly 1.000.000.000 gold). Then I try to give 50k of gold to the other char. Nothing happens.

3 - Suppose that I have 1 Platinum (exactly 1.000.000.000 gold) and I give 1 Platinum to other char: nothing happens.

**Comment by coruja747** [comment]
the 1 seems to be a client bug, since trade window packets doesn't even send this info. The packet to open trade window send this data: "the other char name", "my trade container UID", "the other trade container UID". But it doesn't send any "my name" data, the client seems to use the own char name (stored somewhere) instead get it from server

but 2 and 3 probably will be fixed on next commit

**Comment by GODEXTREME** [comment]
Thanks coruja.
Is there the possibility to know from where the gump get my char name? Maybe from the status gump packet?

**Comment by nefthon** [comment]
Probably when client sends packet http://ruosi.org/packetguide/index.xml#client34 with 'type'==4 to request character's stats, then the server reply back packet http://ruosi.org/packetguide/index.xml#server11 (this packet only sends data up to 'Supported Features' when requesting stats from other characters)

**Comment by GODEXTREME** [comment]
Assuming that chars names won't change, I see no need for 'fixing' this.
Thanks coruja and XuN.
