### ISSUE TITLE
 Memory Item in layer_special (layer 30)  doesn't fire @Timer but fires @destroy

### ISSUE THREAD

**Issue by drk84** [Sphereserver/Source#77]
When a memory item is equipped in layer 30 the @timer trigger doesn't fire,  instead the trigger @destroy is fired. Using last nightly windows build, but it also happening in a older linux version (from 2015 i think?)
Example:

[ITEMDEF i_memory_peacemaking]
ID=i_memory
Name =  Peacemaking
type = t_eq_memory_obj
layer = layer_special
ON=@Create
attr = attr_decay
serv.log Create  <type> <layer> <name> <timer> <attr> <link>

ON=@Destroy
serv.log Firing @destroy..
link.emote Breaks from Peaceamaking Effect
//link.events -e_nocombat

ON=@Timer
serv.log Firing @timer..
link.emote Breaks from Peaceamaking Effect
//link.events -e_nocombat

[FUNCTION testEquipMemory]
serv.newitem i_memory_peacemaking
new.equip
new.timer 5
new.attr = attr_decay
new.link =<uid>
say <new.timer> //Timer value  is shown fine.

**Comment by drk84** [comment]
Changing the type from t_eq_memory_obj to t_eq_script actually fixed the issue, maybe there are other values involved when using t_eq_memory_obj?

**Comment by coruja747** [comment]
typedefs t_eq_* usually are used by internal memories, which is not a good idea replace its default behavior because it can break notoriety, fights, actions, etc. Maybe that's why some triggers like @Timer are not fired on sphere internal memories

you can use t_script instead, which allow you to create a "custom memory" working 100% on script-side instead use sphere internal actions

**Comment by drk84** [comment]
shouldn't t_eq_script be fine?  i remember that the  t_script doesn't allow to equip an item

**Comment by coruja747** [comment]
my fault, it's t_eq_script

it's the same thing of t_script but t_**eq**_script can equip the item like any other memory item
