### ISSUE TITLE
Enhanced Client not showing buy/sell list of goods

### ISSUE THREAD

**Issue by carrotus** [Sphereserver/Source#82]
using enhanced client 4.0.52.2;  list of goods from any vendor not showing

**Comment by carrotus** [comment]
checked again,  it is only the buy list that is not showing.  when you sell an item it shows up in the list; but not when you buy

**Comment by cbnolok** [comment]
Unfortunately this is a known bug and still we haven't found out a way to
fix it

Il 09 gen 2017 12:39, "carrotus" <notifications@github.com> ha scritto:

**Comment by carrotus** [comment]
OK.  Appreciate the work you have done up till now!!!

**Comment by carrotus** [comment]
Hi again.  Just been on the ServUO website tried the latest version of ServUO.  I noticed that they managed to get around this problem and were about to implement the BUY/SELL gump on the Enhanced Client without problem.  However my c# and c++ knowledge is not good enough to look through their code to work out a way to implement this is Sphere.  Maybe someone could have a llok at their coding for the ServUO server and implement this in Sphere!!!

**Comment by coruja747** [comment]
yea I already saw it some months ago, ServUO code doesn't have nothing special, it's just the same old buy/sell engine. Strangely this code works fine on ServUO but not on Sphere

Packets are working fine and the packet order is also the same on both Sphere / ServUO. Also both classic/enhanced clients use these same packets on the same order. But on Sphere it works only on classic clients but not on enhanced clients

I have no idea whats wrong, many devs already tried to fix this thing with no success. Maybe the only way to fix it is using an packet filter to compare each single byte of these packets on Sphere and ServUO. But there's no packet filter tools for enhanced clients yet

**Comment by Ben1028** [comment]
There is a packet filter for enhanced client already, and I have done it. I replicated the exact packets sent by sunuo and it still failed. There is something we are missing somewhere but I can't figure it out

**Comment by carrotus** [comment]
hi again.  It might be nothing, but I have noticed that when working on the enhanced client (like on ServUO) you get an image of the NPC Vendor that you are trying to buy from.  However, on Sphere, you get the same 'shelves' picture for all vendors WITHOUT the image of the NPC Vendor with the enhanced client.  It was as if the NPC was not pick up at all by the enhanced client.

**Comment by coruja747** [comment]
someone can check if the enhanced client buy menu is working on latest 56d builds?

I'm testing here and it seems to be working fine now, I have no idea why, because last time I tried to fix this thing was a year ago. Sphere got many packet improvements since last year, so maybe an random commit had fixed this problem

**Comment by cbnolok** [comment]
The problem is related to the vendor name, see the source2 revisions txt for details

**Comment by coruja747** [comment]
nice finding, I tested here and it's confirmed, buy menu only work on enhanced clients if the vendor have its title set (eg: Lennox the alchemist), otherwise if there's no "the [job]" title set, the item list will be empty. Curiously the client accept any title (eg: "Lennox the hfahsdf") but it MUST start with "the"

anyway, sphere.ini already have VendorTradeTitle=1 set by default and last week I already updated all vendors on sphere_vendors.scp not showing its title properly, so I think we can finally consider this problem fixed 😄
