### ISSUE TITLE
undefined packet sphere 56b and 56c exploding.

### ISSUE THREAD

**Issue by G-Defender** [Sphereserver/Source#83]
Hi sphere 56b and 56c account name: test - password: test - account login. don't char inside the login account. undefined packet is being sent sphere. sphere 56b and 56c ecploding. How can we fix this problem?

23:27:WARNING:1a2:Unknown game packet (0xff) received.
23:27:WARNING:1a2:Unknown game packet (0xff) received.

Another error,

11:39:WARNING:26:Unknown game packet (0x2e) received.
11:39:WARNING:26:Unknown game packet (0xaa) received.
11:39:WARNING:26:Unknown game packet (0x9d) received.
11:39:WARNING:26:Unknown game packet (0x79) received.
11:39:WARNING:26:Unknown game packet (0x78) received.
11:39:WARNING:26:Unknown game packet (0x4d) received.
11:39:WARNING:26:Unknown game packet (0xf3) received.
11:39:WARNING:26:Unknown game packet (0xe3) received.
11:39:WARNING:26:Unknown game packet (0xf5) received.
11:40:WARNING:26:Unknown game packet (0xa2) received.
11:40:WARNING:26:Unknown game packet (0x7b) received.
11:40:WARNING:26:Unknown game packet (0x58) received.
11:40:WARNING:26:Unknown game packet (0x4) received.
11:40:WARNING:26:Unknown game packet (0x46) received.

I'm waiting for your help.

**Comment by cbnolok** [comment]
Which client are you using?


Il 23/01/2017 16:30, BAYRAM KARATAŞ ha scritto:

**Comment by G-Defender** [comment]
56b and 56c.

**Comment by cbnolok** [comment]
56b and 56c are the server (Sphere) versions, we need to know the ultima
online client versions you are using, like 4.0, 5.0, 7.0

Il 27 gen 2017 19:21, "BAYRAM KARATAŞ" <notifications@github.com> ha
scritto:

**Comment by coruja747** [comment]
unfortunately only 56d is supported here on github, because the development of 56b/56c is finished and can't accept more changes, but 56d still in development and accepting changes

anyway, this seems to be a packet error on client-side, because the client is sending to server a list of packets that can only be sent server -> client (and not client -> server) or even packets that doesn't exists. That's why sphere is warning about unknown packets received

**Comment by G-Defender** [comment]
Server, boom there is someone who exploits this vulnerability.

**Comment by coruja747** [comment]
sure, but unfortunately there's no way to fix an bug on 56b/56c, these builds are not in development anymore and we can't "resurrect" these old builds just to apply an fix and release an new 56b or 56c "v2.0". This "new version" already exists and its called 56d, which is the current version in development

that's why we always recommend users to update to latest sphere build, because newest builds have more security protections and more fixes

so instead keep using old builds, I recommend you update to latest 56d where you can get a better support for this. Maybe only the fact that you have updated the server can automatically fix this crash problem, or even it the problem still occur, devs will be able to track it and include the fix on next nightly build

**Comment by G-Defender** [comment]
@coruja747 Sphere 56b does not compile Are the files missing?

https://github.com/Sphereserver/Source/releases

These,

56b-20130616 -> https://github.com/Sphereserver/Source/archive/56b-20130616.zip
56b-20090920 -> https://github.com/Sphereserver/Source/archive/56b-20090920.zip
56b-20080208 -> https://github.com/Sphereserver/Source/archive/56b-20080208.zip

Why would you help me?

**Comment by coruja747** [comment]
I downloaded these source files and the compiler is really broken on all 3. Unfortunately its what I already said, these old files are so messed that doesn't worth even try to use it

It's like use win95 in win10 ages: you will have many issues to install win95 on PC and even after install it you will get even more issues because this windows version is too old.

Sphere is the same thing, the old source code have tons of errors, and even if you spend a lot of time to fix all these compiler errors to finally build an working sphereSvr.exe file, you will also have more errors / security vulnerabilities / ingame bugs / etc if you run your server using this file, because 56b code is old

And another serious reason to not use it: 56b have some security vulnerabilities where pressing an single button in less than 1 minute the hacker can crash your entire server making sphereSvr.exe force-close

I know that you're thinking that will be much easier leave your server using 56b and just find a way to edit some lines on 56b source code. But sometimes the easy way is not the best way to follow, so if your server still using 56b, it's highly recommended update to 56d instead keep trying to use an old 56b code
