### ISSUE TITLE
Missing end statements on scripts make the Sphere hang

### ISSUE THREAD

**Issue by s0ckz** [Sphereserver/Source#90]
On sphere_monsters.scp from scripts, the monster c_dark_father has an script error on @Hit, because the ENDDO is missing, it provokes a hang on Sphere.
So I think the right behaviour would be to warn the programmer that an end statement is missing.

**Comment by Fernandomr88** [comment]
This really needs fixing

**Comment by coruja747** [comment]
Unfortunately I think there's no way to add an warning like this, since Sphere only read script lines in sequence but doesn't know when it's time to stop. And that's exactly what the function ENDDO does: it tell sphere that it reach the end of the DO/ENDDO loop. Without this ENDDO sphere will keep looping forever, and there's no way to make sphere know that there's an missing ENDDO here (although MaxLoopTimes setting on sphere.ini maybe can help with this, Sphere still not know when it's time to stop the loop but MaxLoopTimes will stop the loop when it reach this max loop limit)

The same occur on any other script statement like IF/ENDIF, FOR/ENDFOR, WHILE/ENDWHILE, etc

**Comment by Fernandomr88** [comment]
Yeah, still the script pack needs fixing...

**Comment by coruja747** [comment]
Indeed, I already fixed it here but I'm waiting for some more OSI updates that will be released now in march (eg: new frost mite, triceratops and lion NPCs) to commit all files together

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Scripts/commit/9f5a5e0536d8a98c916fca84338a4a10c9eb92ec
