### ISSUE TITLE
Users Disconnected randomly

### ISSUE THREAD

**Issue by br1luca** [Sphereserver/Source#93]
I have this problem: Users get disconnected from the server without any error.
Looking on the machine network i found this (i dont know if could be related to the problem):
![cattura](https://cloud.githubusercontent.com/assets/19405688/24320799/d10bb2a8-113c-11e7-9a52-893a44ad60f3.PNG)

But i'm not doing nothing during the pikes.
So i think could be some background task of sphere.

Also the crash happens randomly during the day.

**Comment by coruja747** [comment]
since sphere doesn't send huge data to clients, this seems to be some type of small DDoS attack like ICMP/SYN flood. Try enable some extra monitor services on azure to get more network data (eg: connections per second, etc), maybe this will clarify whats happening

If you have apache/IIS server installed but you're not using it, you can also uninstall it or block port 80 on azure firewall because these HTTP servers are common targets of most DDoS attacks. Disabling sphere HTTP server on sphere.ini and blocking ICMP requests on firewall will also help you save outbound bandwidth if you're really under DDoS attack

**Comment by br1luca** [comment]
Hi, are you pretty handy Azure?
Because i have two settings of firewall, one in the azure dashboard and one into VM.
I need to update both or only the VM firewall?

**Comment by coruja747** [comment]
usually you must block the traffic before it reach your VM. But you must take care because if azure firewall get overloaded (even with or without block rules) it will start to disconnect ppl and prevent then to connect again because the network is overloaded. So you must enable this azure extra monitor to check if there's more traffic reaching your server or if all this traffic is just happening on sphere

on the graph this attack wasting 350mb bandwidth in a day is really small, probably just a retarded lammer kid trying to take down your server because someone killed him, so maybe it will be easy to mitigate it using free protections like azure firewall + basic OS firewall

usually the simplest protection against this attack is just block country IP ranges on azure firewall. You can also disable ICMP requests (ping) on windows/linux firewall
